// Code generated by MockGen. DO NOT EDIT.
// Source: internal/storage/types.go
//
// Generated by this command:
//
//	mockgen -source=internal/storage/types.go -package=mocks -destination=internal/mocks/message_storage.go MessageStorage
//

// Package mocks is a generated GoMock package.
package mocks

import (
	model "BlitzQueue/internal/model"
	storage "BlitzQueue/internal/storage"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMessageStorage is a mock of MessageStorage interface.
type MockMessageStorage struct {
	ctrl     *gomock.Controller
	recorder *MockMessageStorageMockRecorder
	isgomock struct{}
}

// MockMessageStorageMockRecorder is the mock recorder for MockMessageStorage.
type MockMessageStorageMockRecorder struct {
	mock *MockMessageStorage
}

// NewMockMessageStorage creates a new mock instance.
func NewMockMessageStorage(ctrl *gomock.Controller) *MockMessageStorage {
	mock := &MockMessageStorage{ctrl: ctrl}
	mock.recorder = &MockMessageStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageStorage) EXPECT() *MockMessageStorageMockRecorder {
	return m.recorder
}

// CleanConsumedMessages mocks base method.
func (m *MockMessageStorage) CleanConsumedMessages() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanConsumedMessages")
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanConsumedMessages indicates an expected call of CleanConsumedMessages.
func (mr *MockMessageStorageMockRecorder) CleanConsumedMessages() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanConsumedMessages", reflect.TypeOf((*MockMessageStorage)(nil).CleanConsumedMessages))
}

// ConfirmMessagesByIds mocks base method.
func (m *MockMessageStorage) ConfirmMessagesByIds(messageIds []string) *storage.MessageStorageError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmMessagesByIds", messageIds)
	ret0, _ := ret[0].(*storage.MessageStorageError)
	return ret0
}

// ConfirmMessagesByIds indicates an expected call of ConfirmMessagesByIds.
func (mr *MockMessageStorageMockRecorder) ConfirmMessagesByIds(messageIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmMessagesByIds", reflect.TypeOf((*MockMessageStorage)(nil).ConfirmMessagesByIds), messageIds)
}

// ConsumeMessages mocks base method.
func (m *MockMessageStorage) ConsumeMessages() ([]*model.ConsumeMessageResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumeMessages")
	ret0, _ := ret[0].([]*model.ConsumeMessageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConsumeMessages indicates an expected call of ConsumeMessages.
func (mr *MockMessageStorageMockRecorder) ConsumeMessages() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeMessages", reflect.TypeOf((*MockMessageStorage)(nil).ConsumeMessages))
}

// ConsumeMessagesWithCustomTime mocks base method.
func (m *MockMessageStorage) ConsumeMessagesWithCustomTime(minutes int) ([]*model.ConsumeMessageResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumeMessagesWithCustomTime", minutes)
	ret0, _ := ret[0].([]*model.ConsumeMessageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConsumeMessagesWithCustomTime indicates an expected call of ConsumeMessagesWithCustomTime.
func (mr *MockMessageStorageMockRecorder) ConsumeMessagesWithCustomTime(minutes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeMessagesWithCustomTime", reflect.TypeOf((*MockMessageStorage)(nil).ConsumeMessagesWithCustomTime), minutes)
}

// GetMoreTimeByIds mocks base method.
func (m *MockMessageStorage) GetMoreTimeByIds(minutes int, messageIds []string) *storage.MessageStorageError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMoreTimeByIds", minutes, messageIds)
	ret0, _ := ret[0].(*storage.MessageStorageError)
	return ret0
}

// GetMoreTimeByIds indicates an expected call of GetMoreTimeByIds.
func (mr *MockMessageStorageMockRecorder) GetMoreTimeByIds(minutes, messageIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMoreTimeByIds", reflect.TypeOf((*MockMessageStorage)(nil).GetMoreTimeByIds), minutes, messageIds)
}

// GetType mocks base method.
func (m *MockMessageStorage) GetType() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetType")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetType indicates an expected call of GetType.
func (mr *MockMessageStorageMockRecorder) GetType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetType", reflect.TypeOf((*MockMessageStorage)(nil).GetType))
}

// PeekMessages mocks base method.
func (m *MockMessageStorage) PeekMessages() ([]*model.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PeekMessages")
	ret0, _ := ret[0].([]*model.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PeekMessages indicates an expected call of PeekMessages.
func (mr *MockMessageStorageMockRecorder) PeekMessages() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PeekMessages", reflect.TypeOf((*MockMessageStorage)(nil).PeekMessages))
}

// PushMessages mocks base method.
func (m *MockMessageStorage) PushMessages(messages ...*model.Message) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range messages {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PushMessages", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// PushMessages indicates an expected call of PushMessages.
func (mr *MockMessageStorageMockRecorder) PushMessages(messages ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushMessages", reflect.TypeOf((*MockMessageStorage)(nil).PushMessages), messages...)
}
