// Code generated by MockGen. DO NOT EDIT.
// Source: internal/storage/queue_storage.go
//
// Generated by this command:
//
//	mockgen -source=internal/storage/queue_storage.go -package=mocks -destination=internal/mocks/storage_mock.go QueueStorage
//

// Package mocks is a generated GoMock package.
package mocks

import (
	model "BlitzQueue/internal/model"
	storage "BlitzQueue/internal/storage"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockQueueStorage is a mock of QueueStorage interface.
type MockQueueStorage struct {
	ctrl     *gomock.Controller
	recorder *MockQueueStorageMockRecorder
	isgomock struct{}
}

// MockQueueStorageMockRecorder is the mock recorder for MockQueueStorage.
type MockQueueStorageMockRecorder struct {
	mock *MockQueueStorage
}

// NewMockQueueStorage creates a new mock instance.
func NewMockQueueStorage(ctrl *gomock.Controller) *MockQueueStorage {
	mock := &MockQueueStorage{ctrl: ctrl}
	mock.recorder = &MockQueueStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueStorage) EXPECT() *MockQueueStorageMockRecorder {
	return m.recorder
}

// CreateQueue mocks base method.
func (m *MockQueueStorage) CreateQueue(arg0 *model.Queue) (*model.Queue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateQueue", arg0)
	ret0, _ := ret[0].(*model.Queue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateQueue indicates an expected call of CreateQueue.
func (mr *MockQueueStorageMockRecorder) CreateQueue(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateQueue", reflect.TypeOf((*MockQueueStorage)(nil).CreateQueue), arg0)
}

// GetMessageStorage mocks base method.
func (m *MockQueueStorage) GetMessageStorage(queue *model.Queue) (storage.MessageStorage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageStorage", queue)
	ret0, _ := ret[0].(storage.MessageStorage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessageStorage indicates an expected call of GetMessageStorage.
func (mr *MockQueueStorageMockRecorder) GetMessageStorage(queue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageStorage", reflect.TypeOf((*MockQueueStorage)(nil).GetMessageStorage), queue)
}

// GetQueueByName mocks base method.
func (m *MockQueueStorage) GetQueueByName(name string) (*model.Queue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQueueByName", name)
	ret0, _ := ret[0].(*model.Queue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQueueByName indicates an expected call of GetQueueByName.
func (mr *MockQueueStorageMockRecorder) GetQueueByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueueByName", reflect.TypeOf((*MockQueueStorage)(nil).GetQueueByName), name)
}
